name: Hourly Weather Email
on:
 schedule:
   - cron: '0 * * * *'
 workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST "https://mourfyorwktimabrrvxb.supabase.co/functions/v1/daily-weather-email"
